version : '3.1'

# MongoDB
services: 
  mongo: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    
# if nother services like:  Postgres, Redis, Elasticsearch, Kibana, Mysql, Postgres
  # postgres: 
  #     image: postgres
  #     restart: always
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: root